### PR TITLE
you can now share from the Loan detail page, toolbar

### PR DESCRIPTION
**Pull request by BrainScraps**
device-2015-04-14-013539

transitions in smoothly, you can share to just about anything yay

### CODE REVIEW

**Comment by zackhsi** [comment]
Should be a menu item

**Comment by BrainScraps** [comment]
The menu layout was acting crazy with all of the animation stuff, so.... I hacked it. :shipit: ? lol

**Comment by zackhsi** [comment]
Let me take a look

**Comment by BrainScraps** [comment]
Thanks!

**Comment by zackhsi** [comment]
share

**Pull request merged**
